### ISSUE TITLE
Toggle Option

### ISSUE THREAD

**Issue by bakinazik** [Soushi-Atsumi/Open-in-Popup#3]
I already wrote it as a review in the addon page, but I wanted to open an issue here in case you don't see it. Can you add a toggle feature that does not refresh the page every time we click it, but only opens/closes it? I need to preserve the current content and the position the page was scrolled to. Thanks.

**Comment by Soushi-Atsumi** [comment]
Hi, bakinazik

Did you mean that you want the pop-up not to be closed when you click the outside of the pop-up?

**Comment by bakinazik** [comment]
the popup should close but keep it open in the background. should function as a toggle. idk is that possible..

**Comment by Soushi-Atsumi** [comment]
Sadly it is impossible. This is the behavior of the Firefox's popup. According to [this document](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups#specifying_a_popup), it always loads a page when it is shown and it always unloads a page when it is closed. And there are no APIs to handle this behavior.

**Comment by bakinazik** [comment]
so sad to hear. they literally killing the potential.. floorp is trying to add a sidebar to the interface, but there are still many shortcomings.  it's not nice for the gecko to be left behind. thanks anyway.
